config/routes.rb
Rails.application.routes.draw do

  match 'albums/select' => 'albums/select', via: [:get, :post]
  get '/albums/:album/photo/:photo/add' => "albums#add_photo"
  get '/albums/get_tag_list' => "albums#get_tag_list"
  resources :albums

  get 'pages' => 'pages#index'

  match "photos/(q/*query)" => "photos#index", :via => [:post, :get]
  get '/photos/get_tag_list' => 'photos#get_tag_list'
  get '/photos/valid_date/:type/:date' => 'photos#valid_date'
  resources :photos, :except => [:create, :index]
  get '/photos/:id/image/:size' => 'photos#image'
  get '/photos/:id/rotate/(:degrees)' => 'photos#rotate'
  get '/photos/:id/add_comment' => 'photos#add_comment'
  get '/photos/:id/like' => 'photos#like'
  get '/photos/:id/addtag' => 'photos#addtag'
  get '/photos/:id/removetag' => 'photos#removetag'
  get '/photos/:id/show_small' => 'photos#show_small'



  get '/catalogs/migrate' => 'catalogs#migrate'
  get '/catalogs/authorize' => 'catalogs#authorize'
  put '/catalogs/authorize' => 'catalogs#authorize'
  get '/catalogs/authorize_callback' => 'catalogs#authorize_callback'
  resources :catalogs
  get '/catalogs/:id/dashboard' => 'catalogs#dashboard'
  get '/catalogs/:id/get_catalog' => 'catalogs#get_catalog'
  match "/catalogs/:id/edit" => "catalogs#edit", via: [:get, :post]
  get "/catalogs/:id/destroy" => "catalogs#destroy"
  match '/catalogs/:id/import' => 'catalogs#import', via: [:get, :post]

  get '/locations/create'
  get '/locations/new'
  get '/locations/lookup_address'
  get '/locations/lookup'
  get 'locations/new_from_coordinate_string' => 'locations#new_from_coordinate_string'
  get 'locations/typeahead/:query' => 'locations#typeahead'
  resources :locations
  get '/locations/:id/view' => 'locations#view'

  post 'bucket/:id/toggle' => 'bucket#toggle'
  post 'bucket/:id/add' => 'bucket#add'
  post 'bucket/:id/remove' => 'bucket#remove'
  get  'bucket/list' => 'bucket#list'
  get  'bucket' => 'bucket#index'
  get  'bucket/clear' => 'bucket#clear'
  get  'bucket/count' => 'bucket#count'
  get  'bucket/save' => 'bucket#save_to_album'
  get  'bucket/delete_photos' => 'bucket#delete_photos'
  get '/bucket/rotate/(:degrees)' => 'bucket#rotate'
  get  'bucket/like' => 'bucket#like'
  get  'bucket/unlike' => 'bucket#unlike'
  get  'bucket/add_comment' => 'bucket#add_comment'
  get  'bucket/edit' => 'bucket#edit'
  patch  'bucket/update' => 'bucket#update'

  resources :photofiles
  get 'photofiles/:id/photoserve' => 'photofiles#photoserve'
  patch 'photofiles/:id/rotate' => 'photofiles#rotate'
  get 'photofiles/:id/phash' => 'photofiles#phash'

  post 'jobs/list' => 'jobs#list'
  resources :jobs

  Rails.application.routes.draw do
    resources :users, controller: 'users', only: [:create, :edit, :update]
  end



  mount Resque::Server.new, at: "/resque"

  root to: 'photos#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :latitude, :longitude, :country, presence: true
  has_many :photos
  reverse_geocoded_by :latitude, :longitude

  scope :distinct_countries, -> {
    ary = select(:country).distinct.map { |c| [c.country] }.unshift([''])
    ary.delete([nil])
    ary.sort_by{|el| el[0] }
  }
  scope :distinct_cities, -> {
    ary = select(:city).distinct.map { |c| [c.city] }.unshift([''])
    ary.delete([nil])
    ary.sort_by{|el| el[0] }
  }

  def self.geolocate
    Photo.where{location_id.eq(nil)}.each do |photo|
      UtilLocator.perform_later photo.id
    end
  end

  def map_url
    url = Rails.configuration.x.phototank["filestoreurl"]
    if self.map_image_id == nil
      "#{url}/photofiles/1/photoserve"
    else
      "#{url}/photofiles/#{self.map_image_id}/photoserve"
    end
  end

  def self.locate_photo(photo)
    @photo = photo
    if no_coordinates
      return true
    elsif reuse_location
      return true
    elsif geosearch
      pf = PhotoFilesApi::Api::new
      response = pf.create @photo.location.get_google_map, nil, nil, 'maps'
      @photo.location.update(map_image_id: response[:id])
      return true
    else
      @photo.location = get_no_location
      return true
    end


  end

  def get_google_map(zoom=10, size="350x300")
    marker = "#{self.latitude}%2C#{self.longitude}"
    return "http://maps.google.com/maps/api/staticmap?size=#{size}&sensor=false&zoom=#{zoom}&markers=#{marker}"
  end

  def self.no_location
    Rails.cache.fetch("no_location", expires_in: 12.hours) do

      return get_no_location
    end
  end

  def self.typeahead_search(query)
    match  = Location.where("address LIKE ?", "%#{query}%").select('id, address')

    n = match.map do |e|
      {:id=> e.id, :value=>e.address}
    end

    return n
  end

  def get_location
    self.geocoder_lookup
  end

  def coordinate_string
    self.latitude.to_s + "," + self.longitude.to_s
  end

  def geocoder_lookup
    if geo_location = Geocoder.search(self.coordinate_string).first
      if geo_location.data["error"].blank?
        self.country = geo_location.country
        self.city = geo_location.city
        self.suburb = geo_location.suburb
        self.postcode = geo_location.postal_code
        self.address = geo_location.address
        self.state = geo_location.state
        self.longitude = geo_location.longitude
        self.latitude = geo_location.latitude
      end
    end
  end

  private
  def self.no_coordinates()
    if @photo.latitude.blank? || @photo.longitude.blank?
      @photo.location = get_no_location
      return true
    end
  end

  def self.reuse_location()

    similar_locations = @photo.nearbys(1).where.not(location_id: nil)
    if similar_locations.count(:all) > 0
      @photo.location = similar_locations.first.location
      return true
    end
  end

  def self.geosearch

    begin
      if geo_location = Geocoder.search(@photo.coordinate_string).first
        if geo_location.data["error"].blank?
          new_location = Location.new
          new_location.country = geo_location.country
          new_location.city = geo_location.city
          new_location.suburb = geo_location.suburb
          new_location.postcode = geo_location.postal_code
          new_location.address = geo_location.address
          new_location.state = geo_location.state
          new_location.longitude = geo_location.longitude
          new_location.latitude = geo_location.latitude
          new_location.save
          @photo.location = new_location
          return true
        else
          @photo.location = temp_location
        end
      else
        @photo.location = temp_location
      end
    rescue Exception => e
      @photo.location = temp_location
    end
  end


  def self.get_no_location
    loc = Location.where(status:100)
    if loc.length > 0
      return loc.first
    else
      loc = Location.create(latitude:0, longitude:0, country:"N/A", status:100)
      return loc
    end
  end

  def self.temp_location
    loc = Location.where(status:200)
    if loc.length > 0
      return loc.first
    else
      loc = Location.create(latitude:0, longitude:0, country:"N/A", status:200)
      return loc
    end
  end


end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :require_login

  def index

    if request.xhr?
      order = :country
      order = params[:order] unless not params.has_key?(:order)
      query = "%#{params[:q]}%"
      query ||="%"

      @locations = Location.where("address LIKE ?", query).where("latitude != 0 AND longitude != 0").order(order).paginate(:page => params[:page], :per_page=>30)

    end
  end





  def show
    @bucket = session[:bucket]
    @location = Location.find(params[:id])

    #Get photos
    @photos = @location.photos.paginate(:page => params[:page], :per_page => 40)

    #If this was requested from an ajax call it should be rendered with slim view
    if request.xhr?
      render :partial=>"photos/grid"
    end
  end

  def view

    @view = 'grid'

    @bucket = session[:bucket]
    @photos = Photo.where(:location => params[:id]).page params[:page]
    @location = Location.find(params[:id])
    @bucket = session[:bucket]
    #If this was requested from an ajax call it should be rendered with slim view
    if request.xhr?
      render :partial=>"photos/grid"
    end
  end

  def lookup
    Location.geolocate
    redirect_to :action => 'index'
  end

  def typeahead
    search  = Location.typeahead_search(params[:term])
    render json: search
  end

  def new_from_coordinate_string
    new_location = Location.new
    new_location.longitude = params[:longitude]
    new_location.latitude = params[:latitude]
    new_location.get_location
    render json: new_location
  end

  def new
    @return_url = request.referer
  end

  def create
    new_location = Location.new(params.permit(:latitude, :longitude, :country, :city, :address, :state, :postcode, :road, :suburb))
    if new_location == nil or new_location.latitude == nil
      render status: 406
    elsif new_location.nearbys(1).count(:all) > 0
      render status: 409
    else
      new_location.save
      render json: new_location if request.xhr?
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.haml
.box.box-primary
  .box-header.with-border
    %h3.box-title Pick location

    .box-body
      %input#pac-input.controls{:type=>"text", :placeholder=>"Search Box"}
      .col-lg-8#map{:style=>"height: 400px; width: 65%;"}
      .col-lg-4
        #spinner.h4
        #address_block{:style=>'display: none'}
          %dl.dl-horizontal.pull-left
            %dt Country
            %dd#country

            %dt City
            %dd#city

            %dt Address
            %dd#address
          %a.btn.btn-default.pull-right#add_location{:href=>"#{@return_url}", :role=>"button"} Add Location




:css
  .controls {
    margin-top: 10px;
    border: 1px solid transparent;
    border-radius: 2px 0 0 2px;
    box-sizing: border-box;
    -moz-box-sizing: border-box;
    height: 32px;
    outline: none;
    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
  }

  #pac-input {
    background-color: #fff;
    font-family: Roboto;
    font-size: 15px;
    font-weight: 300;
    margin-left: 12px;
    padding: 0 11px 0 13px;
    text-overflow: ellipsis;
    width: 300px;
  }

  #pac-input:focus {
    border-color: #4d90fe;
  }

  .pac-container {
    font-family: Roboto;
  }

  #type-selector {
    color: #fff;
    background-color: #4d90fe;
    padding: 5px 11px 0px 11px;
  }

  #type-selector label {
    font-family: Roboto;
    font-size: 13px;
    font-weight: 300;
  }
  #target {
    width: 345px;
  }

app/views/locations/_list.html.haml
-# delete file

.row
  .col.s12.cards-container
    =render :partial => @locations

:css
  .cards-container {
    column-break-inside: avoid;
    .card {
      display: inline-block;
      overflow: visible;
    }
  }

app/views/locations/index.html.haml
=content_for :title, "Locations"
=content_for :subtitle, "all"

=react_component 'Locations'

app/views/locations/new.html.haml
= render :partial => 'form'

app/views/locations/show.html.haml
=content_for :title, @location.country
=content_for :subtitle, @location.address
.row
  = render :template => 'photos/_index'

app/views/locations/view.html.haml
=content_for :title, @location.address
=content_for :subtitle, Location

= render :template => 'photos/_index'

app/views/locations/xindex.html.haml
=content_for :title, "Locations"
=content_for :subtitle, "all"

.box
  .box-header.with-border
    .pull-right
      .btn-group.btn-group-sm{"aria-label" => "...", :role => "group"}
        = link_to "New location", "/locations/new", class:"btn btn-default"
        .btn-group{:role => "group"}
          %button.btn.btn-default.dropdown-toggle.btn-sm{"data-toggle" => "dropdown", :type => "button"}
            Order by
            %span.caret
          %ul.dropdown-menu
            %li
              %a{:href => "/locations?order=country"} Country
            %li
              %a{:href => "/locations?order=city"} City
            %li
              %a{:href => "/locations?order=address"} Address
        .input-group.input-group-sm
          %input#search-locations.form-control{:placeholder => "Search for...", :type => "text", :value => "#{params[:q]}"}
  .box-body
    %table.table
      %thead
        %tr
          %th Country
          %th City
          %th Address
          %th # photos
          %th
          %th
          %th
      %tbody
        - @locations.each do |location|
          %tr
            %td= location.country
            %td= location.city
            %td= location.address
            %td= location.photos.count
            %td= link_to icon('picture-o'), controller: 'locations', action: 'view', id: location
            %td= link_to icon('eye'), location_path(location)
            %td= link_to icon('pencil'), edit_location_path(location)


  .box-footer

    = will_paginate @locations